# Generated by Django 4.0.3 on 2023-04-22 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tbpatientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbPatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.CharField(blank=True, max_length=45, null=True)),
                ('is_fever', models.BooleanField(blank=True, null=True)),
                ('total_lung_capacity', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
