# Generated by Django 4.0.3 on 2023-04-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tbpatientreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbpatientinfo',
            old_name='suger_level',
            new_name='sugar_level',
        ),
    ]
